# Muda prefixo de Ctrl+b pra Ctrl+a (mais ergonômico)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Divide panes com | e - em vez de % e "
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Navega entre panes com Alt+seta (sem prefixo)
# Detecta se o pane atual é nvim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Navegação
bind -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

# Resize
bind -n M-Left if-shell "$is_vim" 'send-keys M-Left' 'resize-pane -L 3'
bind -n M-Down if-shell "$is_vim" 'send-keys M-Down' 'resize-pane -D 3'
bind -n M-Up if-shell "$is_vim" 'send-keys M-Up' 'resize-pane -U 3'
bind -n M-Right if-shell "$is_vim" 'send-keys M-Right' 'resize-pane -R 3'
bind r source-file ~/.config/tmux/tmux.conf \; display "Config recarregado"

set -g mode-keys vi
set -s extended-keys on

# Mouse ativo
set -g mouse on

# Limite de caracteres de status
set -g status-left-length 50

# Indexa windows e panes a partir de 1
set -g base-index 1
set -g pane-base-index 1

# Renumera windows automaticamente
set -g renumber-windows on

# Histórico maior
set -g history-limit 10000

# Cores 256
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Sem delay no Esc (importante pro Neovim)
set -sg escape-time 0

# Statusbar embaixo
set -g status-position bottom
set -g status-style 'bg=#1a1a1a fg=#888888'

# Janela ativa em destaque
set -g window-status-current-style 'fg=#d4af37 bold'

# Sem bordas desnecessárias
set -g pane-border-style 'fg=#333333'
set -g pane-active-border-style 'fg=#d4af37'

# Status direito limpo
# set -g status-right '#[fg=#888888]%H:%M '
# set -g status-left '#[fg=#d4af37] #S '

# set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @tokyo-night-tmux_theme night   # night (default) | storm | moon | day
# set -g @tokyo-night-tmux_transparent 0 # transparent background
# set -g @tokyo-night-tmux_show_git 1             # local git status
# set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
# set -g @tokyo-night-tmux_show_netspeed 1        # network speed
# set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
# set -g @tokyo-night-tmux_show_music 0           # now playing
# set -g @tokyo-night-tmux_show_path 0            # current path
# set -g @tokyo-night-tmux_show_hostname 0        # machine hostname

set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor "moonlight_dark"  # Optional: defaults to lagoon_dark

# Initialize TPM (mantém essa linha SEMPRE por último)
run '~/.tmux/plugins/tpm/tpm'
